services:
  keel:
    host: 0.0.0.0
    port: 7002
    baseUrl: http://spin-keel.spinnaker:7002
    enabled: true
  clouddriver:
    host: 0.0.0.0
    port: 7002
    baseUrl: http://spin-clouddriver.spinnaker:7002
    enabled: true
  clouddriverCaching:
    host: 0.0.0.0
    port: 7002
    baseUrl: http://spin-clouddriver-caching.spinnaker:7002
    enabled: false
  clouddriverRo:
    host: 0.0.0.0
    port: 7002
    baseUrl: http://spin-clouddriver-ro.spinnaker:7002
    enabled: false
  clouddriverRoDeck:
    host: 0.0.0.0
    port: 7002
    baseUrl: http://spin-clouddriver-ro-deck.spinnaker:7002
    enabled: false
  clouddriverRw:
    host: 0.0.0.0
    port: 7002
    baseUrl: http://spin-clouddriver-rw.spinnaker:7002
    enabled: false
  deck:
    host: 0.0.0.0
    port: 9000
    baseUrl: http://af7580d35cc7043d6bdbc8eb709ad88f-1674755148.us-east-2.elb.amazonaws.com
    enabled: true
  echo:
    host: 0.0.0.0
    port: 8089
    baseUrl: http://spin-echo.spinnaker:8089
    enabled: true
  echoScheduler:
    host: 0.0.0.0
    port: 8089
    baseUrl: http://spin-echo-scheduler.spinnaker:8089
    enabled: false
  echoWorker:
    host: 0.0.0.0
    port: 8089
    baseUrl: http://spin-echo-worker.spinnaker:8089
    enabled: false
  fiat:
    host: 0.0.0.0
    port: 7003
    baseUrl: http://spin-fiat.spinnaker:7003
    enabled: false
  front50:
    host: 0.0.0.0
    port: 8080
    baseUrl: http://spin-front50.spinnaker:8080
    enabled: true
  gate:
    host: 0.0.0.0
    port: 8084
    baseUrl: http://a88d5789908904f2395b15a4f784f9b9-1031842537.us-east-2.elb.amazonaws.com
    enabled: true
  igor:
    host: 0.0.0.0
    port: 8088
    baseUrl: http://spin-igor.spinnaker:8088
    enabled: false
  kayenta:
    host: 0.0.0.0
    port: 8090
    baseUrl: http://spin-kayenta.spinnaker:8090
    enabled: false
  orca:
    host: 0.0.0.0
    port: 8083
    baseUrl: http://localhost:8083
    enabled: true
  redis:
    host: 0.0.0.0
    port: 6379
    baseUrl: redis://spin-redis.spinnaker:6379
    enabled: true
  rosco:
    host: 0.0.0.0
    port: 8087
    baseUrl: http://spin-rosco.spinnaker:8087
    enabled: true
  monitoringDaemon:
    host: 0.0.0.0
    port: 8008
    baseUrl: http://spin-monitoring-daemon.spinnaker:8008
    enabled: false
global.spinnaker.timezone: America/Los_Angeles
